### ISSUE TITLE
It's saying that the syntax is invalid or that pptx2md isn't defined. I'm in Spyder on Mac.

### ISSUE THREAD

**Issue by classicrob** [ssine/pptx2md#11]
![image](https://user-images.githubusercontent.com/46608303/97486293-dc43a280-1920-11eb-905e-f6c8bc0ba19d.png)

**Comment by classicrob** [comment]
I would try running it in terminal, but Mac terminal is stuck at python 2.7

**Comment by ssine** [comment]
Mac's terminal doesn't stuck at python2.7, please consider using a python version management tool(highly recommended), or try this:

* uninstalling pptx2md in python2
* install python3
* reinstall it by `pip3 install pptx2md` or `python3 -m pip install pptx2md`.
* try `python3 -m pptx2md xxx.pptx`

**Comment by classicrob** [comment]
Thank you!
