### ISSUE TITLE
Can you add on readme how do I use all those flags?

### ISSUE THREAD

**Issue by biel-correa** [ssine/pptx2md#13]
I can't really understand how am I suppose to use the -o flag and I think other people don't know either.

**Comment by ssine** [comment]
It's a common argument for command line tools, e.g. `pptx2md xxx.pptx -o a.md` will write the output to a.md in current directory.

It would be verbose to raise examples for each of the flags, I'll consider adding them when a second issue about flag usage appears.

**Comment by biel-correa** [comment]
Ok, thanks.
