### ISSUE TITLE
The conversion to md is interrupted.

### ISSUE THREAD

**Issue by phys-ken** [ssine/pptx2md#15]
Hi. This software is great！

When pptx2md reach the slide that contains the certain types of images (created in power point,like arrows), the process is interrupted.  Perhaps pillow is throwing an error when trying to process an image that pillow can't load.  The proof is that --disable image eliminates the error.

Translated from Japanese to English by Google Translate.

**Comment by ssine** [comment]
Hi, I failed to reproduce this error, it works on pptx with arrows. Would you please send me a file causing this error?

**Comment by phys-ken** [comment]
Thank you for your reply.
I just sent it by email.

**Comment by ssine** [comment]
wmf formatted images are automatically converted to png, but there is a known issue that wmf format cannot be loaded by pillow under linux. You can add `--disable_wmf` argument (as listed in readme) to skip this conversion, and that should solve the problem.

**Comment by phys-ken** [comment]
Thank you!!!!!!!
It worked exactly with this argument.

I didn’t understand about wmf. It was a good opportunity for me.

I appreciate your quick response.

**Comment by allefeld** [comment]
The `--disable_wmf` argument is good to avoid the exception and interruption. But this way, one loses track of where those images were supposed to be if one converts them manually later.

I propose to change the behavior such that the img code is still written to the Markdown output, referencing the extracted WMF file. This way there is a reminder in the Markdown code which images need to converted, and the code is easy to fix by changing `.wmf` to e.g. `.png`.
