### ISSUE TITLE
🐛 BUG: Converter creating some "\" after breakline

### ISSUE THREAD

**Issue by biel-correa** [ssine/pptx2md#16]
## PPTX
```
Para fazer classificação das áreas de forma 
robusta, é preciso elaborar uma análise de 
risco detalhada para identificar as fontes 
```

## Markdown
```
Para fazer classificação das áreas de forma robusta\, é preciso elaborar uma análise de risco detalhada para identificar as fontes 
```

## More details
As you can see it doesn't happen every time, although I've seen an entire file full of "\"

**Comment by biel-correa** [comment]
Tell me if you need the file. The text is in pt-br.

**Comment by ssine** [comment]
hi @biel-correa , I cannot reproduce this bug on a new pptx file, pls send yours to `liu.siyao@qq.com` for debugging, thanks.

**Comment by biel-correa** [comment]
Just sent it, the title is 🐛 BUG: Converter creating some "\" after breakline
@ssine

**Comment by ssine** [comment]
This is not a bug, but a feature that escapes special characters to avoid unexpected situation. For example, if a text with link contains "]()", the rendered markdown will be `[text]()](link)` which results in an empty link, escaping them with `[text\]\(\)](link)` will avoid the issue.

You can disable this feature by adding disable_escaping argument, like `pptx2md --disable_escaping '.\modulo 3.pptx'`. Remember to upgrade to the newest version: `pip install --upgrade pptx2md==0.7.8`

**Comment by biel-correa** [comment]
Thanks bro
