### ISSUE TITLE
Markdown syntax for images

### ISSUE THREAD

**Issue by allefeld** [ssine/pptx2md#19]
The Markdown output uses HTML `<img>` tags for images, though there is [dedicated Markdown syntax](https://daringfireball.net/projects/markdown/syntax#img) for it:

```
![Alt text](/path/to/img.jpg)
![Alt text](/path/to/img.jpg "Optional title")
```

Could you please support the Markdown syntax, at least as an option? The advantage is that this allows further conversion to formats other than HTML, e.g. via Pandoc. My application is to convert `pptx` to Markdown, and then use Pandoc's beamer option to create slides.

I'm guessing the reason for this choice is that this syntax does not allow to specify the image width. Here you could use Pandoc's syntax inspired by PHP Markdown extra:
```
![](file.jpg){ width=50% }
```
Of course only optionally.

**Comment by ssine** [comment]
That makes sense. Since image width are not allowed in basic markdown syntax, if `--image-width` is not set, images will be but in markdown syntax. A new version is published, please update with `pip install --upgrade pptx2md==1.0.0` and try again.

Note that `_`s in arguments are replaced by `-`s.

**Comment by allefeld** [comment]
Great, thanks!
