### ISSUE TITLE
Feature request: Table conversion

### ISSUE THREAD

**Issue by Taakefyrsten** [ssine/pptx2md#20]
It'd be lovely if this program could take inserted spreadsheets to make markdown tables. Currently I'm C/V any spreadsheets into https://tabletomarkdown.com/convert-spreadsheet-to-markdown/ to convert any spreadsheets to tables.

**Comment by ssine** [comment]
I'll evaluate this feature when I have time.

**Comment by ssine** [comment]
Hi, now tables are converted to markdown too. You can install the new version with `pip install pptx2md==1.1.1` and try it out.
