### ISSUE TITLE
Spaces not correctly converted

### ISSUE THREAD

**Issue by minostauros** [ssine/pptx2md#26]
### Environment
MacBook Pro (16-inch, 2021) M1 Pro MacOS 12.1
Python 3.8.9
```
Package     Version
----------- -------
lxml        4.7.1
Pillow      9.0.0
pip         21.3.1
pptx2md     1.1.1
python-pptx 0.6.21
rapidfuzz   1.9.1
setuptools  49.2.1
six         1.15.0
wheel       0.33.1
XlsxWriter  3.0.2
```

### Reproduce
Input: [test.pptx](https://github.com/ssine/pptx2md/files/7805531/test.pptx)
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/6764739/148013599-de8e15fe-0e64-4d61-9eab-088bcfccc411.png">

Output:
```
# TE;ST

* Lorem ipsum
  * dolor sitamet\,
  * consectetur/adipiscingelit\.
  * Phasellus/tortorturpis\,
  * semper etporttitorvel\,
    * ullamcorpersempermassa\.
* Phasellustempor
  * felisutnullafermentum
  * hendrerit\. Donec et lacinia ipsum\.
  * Fuscelectuslacus\,
    * auctor aquama\,
    * sagittisvehiculatortor\.
    * Pellentesqueiaculisfelisodio\,
  * vitaescelerisque
```
# TE;ST

* Lorem ipsum
  * dolor sitamet\,
  * consectetur/adipiscingelit\.
  * Phasellus/tortorturpis\,
  * semper etporttitorvel\,
    * ullamcorpersempermassa\.
* Phasellustempor
  * felisutnullafermentum
  * hendrerit\. Donec et lacinia ipsum\.
  * Fuscelectuslacus\,
    * auctor aquama\,
    * sagittisvehiculatortor\.
    * Pellentesqueiaculisfelisodio\,
  * vitaescelerisque

**Comment by ssine** [comment]
Fixed. Upgrade to the newest version and try again: `pip install --upgrade pptx2md==1.1.2`
