### ISSUE TITLE
License

### ISSUE THREAD

**Issue by drewbrophy** [ssine/pptx2md#27]
What is the license on this repo? Thank you in advance.

**Comment by ssine** [comment]
Not decided yet, I tend to use LGPL. What's your scenario?

**Comment by MartinPacker** [comment]
I cannot even ask my organisation to allow me to use it without a suitable licence. (MIT is what I've used in my projects.)

**Comment by hguhlich** [comment]
Hi @ssine,

Thank you for this really cool converter. Could you please add a license to the repository? Without a license, it's unclear how the code can be used or modified, and it might put users at risk of legal issues, see for example [here](https://choosealicense.com/no-permission/).

Thanks!

**Comment by ssine** [comment]
The project is now licensed under apache-2.0 , all the versions after 2.0.4 should be safe to use now.
