### ISSUE TITLE
wmf / emf

### ISSUE THREAD

**Issue by Dibal** [ssine/pptx2md#29]
(great tool!)

Sometimes Powerpoint embeds images as WMF files (which libreoffice converts to EMF). Even if it is a vector file Pillow should be able to translate it to pixel image -- which may be better than nothing.
Unfortunately your program fails to recognize WMF files: "cannot find loader for this WMF file". It even does not proceed without images but stops processing.

Question: do you think you could extend your program in a way that it can handle WMF files?

**Comment by ssine** [comment]
As written in the README, you can use `--disable-wmf` option to ignore these images in linux.

And for the advice, yes, many aspects of this tool is not well designed three years ago. I will refactor some parts of it when I have time.

**Comment by Dibal** [comment]
In case you find the time to remedy the wmf problem:

If I use the --disable-wmf switch it is OK for most of the slides. But it stops on one slide with the error message:

PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fc820985360>

There are two wmf-images in the pptx-slide. When I remove them the error disappears.

**Comment by Dibal** [comment]
Or at least keep the reference to the image in the markdown file: 
instead of removing reference to images please write:
 [xxx](img/image.wmf).

Then it is easy to change 1)  all references to "image.png" and 2) extract all images from pptx-folder and convert them via imagemagick-convert from wmf to png (not all images are properly converted).

**Comment by ssine** [comment]
@Dibal Would you please send me a pptx file with the problematic wmf images? Some test is needed. My email address is `liu.siyao@qq.com`

**Comment by ssine** [comment]
Or you can just try the latest version 1.2.0 and check if there's still any problem.

**Comment by Dibal** [comment]
Amazing! Most of the images are now converted to png. Where the conversion fails no error message is thrown and the program processes the whole file. Some wmf files are difficult to convert, even imagemagick fails.In some cases libreoffice-CLI is more successful -- but the program has no idea about the size of the image.

You may find a large demo excel file here: https://cbrell.de/blog/wp-content/uploads/2022/02/Statistik-von-Null-auf-Hundert-Dozentenmaterial.zip

Obervations:

* about 50% of wmf vector images are not converted.
* It may be helpful if the markdown-output file keeps an image-reference to the non converted wmf-image. I don't know if this is a benefit for windows-users. But at least it helps to find missing images (perhaps keeping references to non convertable wmf files may be an option)
* Tables are well transformed -- but lines drawn on tables are lost.

**Comment by ssine** [comment]
I think there are references to non converted wmf-images already. Tables are not well supported by markdown itself.

The issue is resolved, thanks for testing.
