### ISSUE TITLE
exit(0) call without importing sys

### ISSUE THREAD

**Issue by Kugeleis** [ssine/pptx2md#38]
In __init__.py line 100 calls `exit(0)` without importing it from sys with `from sys import exit` and leads to an error.    
However, using pptx2md within another script it terminates if above is fixed which might not be wanted. Better return with a nozero exit value.

**Comment by ssine** [comment]
`exit` is a builtin function, it shouldn't cause an error if `sys.exit` is not used in this case, although `sys.exit` it's preferred. A nonzero return code is resonable.

Busy at the moment, a PR is welcomed.

**Comment by ssine** [comment]
fixed in 1.6.0
