### ISSUE TITLE
Speaker's note

### ISSUE THREAD

**Issue by albertyckwok** [ssine/pptx2md#42]
Is there way to export Speaker's note too?
Thanks
Albert

**Comment by frettig-radiox** [comment]
I was looking for this feature too:

It could be exported in pandoc stye:
https://www.uv.es/wikibase/doc/cat/pandoc_manual_2.7.3.wiki?165

Example:

::: notes

This is my note.

- It can contain Markdown
- like this list

:::

**Comment by albertyckwok** [comment]
Thanks @frettig-radiox , do you mean that pandoc can export PPTX to MD that include speaker's note?

**Comment by frettig-radiox** [comment]
No, pandoc converts md to pptx including speaker's note.

**Comment by ssine** [comment]
Just implemented this, please install the new version with `pip install pptx2md==1.5.0` and try again. @albertyckwok @frettig-radiox

**Comment by frettig-radiox** [comment]
thx
