### ISSUE TITLE
[Feature Request] Support hyperlinks in tables

### ISSUE THREAD

**Issue by mike-g-msft** [ssine/pptx2md#46]
Not sure if this is expected to work or not, but currently it does not. Would you consider supporting preserving hyperlinks within table cells?

**Comment by ssine** [comment]
It's possible for markdown syntax, but requires a major refactor of the code. I'll consider that when I have time.

Will keep this issue open until supported.

**Comment by ssine** [comment]
This is supported in the newest version (2.0.3) now.
