### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by sharky98** [ssine/pptx2md#54]
I am trying to install it. From a very bare global installation I did `pip install pptx2md`. When trying to run `pptx2md --help`, I had many `ModuleNotFoundError: No module named '[pkg name]'`.

- numpy
- matplotlib
- scipy

**Comment by doeringp** [comment]
I could solve problem by installing the required dependencies manually. But these packages should be installed automatically when executing `pip install pptx2md`.

```bash
pip install numpy
pip install matplotlib
pip install scipy
```

**Comment by ssine** [comment]
This should be fixed in the newest version now.
