### ISSUE TITLE
Image path is URL-encoded in exported markdown

### ISSUE THREAD

**Issue by sharky98** [ssine/pptx2md#55]
When exporting using basic options (only the output), the images are extracted correctly, but they are inserted in the markdown using URL-encoded path. This lead to not able to display the image.

## Actual output
```md
![](img%5Cmy-pptx0.png)
```

## Expected output
```md
![](img/my-pptx0.png)
```

Just to note, I am using this one for a one-of conversion of 2 files. A simple search and replace is enough for me. But it might not be for someone using `pptx2md` in a workflow.

**Comment by ssine** [comment]
The newest version should have fixed the issue. reopen if it still exists

**Comment by vincentsys** [comment]
I still have this issue with the current version (but I cannot repoen the issue) @ssine
