### ISSUE TITLE
The ability to change "\n---\n" to a custom string when --enable-slides is set.

### ISSUE THREAD

**Issue by PAHXO** [ssine/pptx2md#60]
I would like to have the ability to change "\n---\n"  to a different one.

one that contains information about the current number of the slide.

preferably one that I can set via the cli.

for example --enable-slides --slides-separator=[---(slide_number)---] or something like that instead of "\n---\n".

Thanks, really like the project.

**Comment by ssine** [comment]
That's too little a feature to add into the arguments. Perhaps you can edit [this part](https://github.com/ssine/pptx2md/blob/392465577bd6c72a848c7f63dab5eeb359133089/pptx2md/outputter.py#L80) after installation, and change it to whatever you want.
