### ISSUE TITLE
Add dependencies of Numpy into toml file

### ISSUE THREAD

**Issue by Piorosen** [ssine/pptx2md#66]
when i installed pptx2md to venv, i get error about no module named 'numpy'. 
so, could you add numpy for more easily install about pptx 2md into pyproject.toml?

Thank you.

![Screenshot 2024-09-22 at 5 39 04 PM](https://github.com/user-attachments/assets/f418d34c-89d9-4265-9fc3-c179673d0c47)
![Screenshot 2024-09-22 at 5 40 32 PM](https://github.com/user-attachments/assets/18d85910-4339-44bd-bd75-d3127569fc01)

**Comment by Piorosen** [comment]
oh, my mistake,  matplotlib, scipy.

**Comment by Amatewasu** [comment]
@Piorosen Thank you for your issue. Have you succeeded at making `pptx2md` works? :)

**Comment by Piorosen** [comment]
YES! this project made a result of good quallity. 
However. My pptx had complex images such as scattered images and text boxes, which were not expressed well in markdown.
T.T, Thank you about answer! have a good day!

**Comment by Amatewasu** [comment]
Ah it works for me as well, thanks!
