### ISSUE TITLE
--disable-color is not working

### ISSUE THREAD

**Issue by ijmitch** [ssine/pptx2md#67]
I can see treatment of `disable_color` in [an old commit](https://github.com/ssine/pptx2md/commit/6c3ced7059dab831538229a4935a76ad64fb23f4), but there's no sign of it making any difference now.

**Comment by ssine** [comment]
That might be missed in a recent refactor. Thanks for the fix.
I will release a new version with the fix within today.

**Comment by ssine** [comment]
released in 2.0.6
